# Generated by Django 4.0 on 2022-09-26 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('img', models.ImageField(upload_to='product')),
                ('desc', models.TextField(max_length=122)),
                ('stock', models.IntegerField(max_length=122)),
                ('available', models.BooleanField(max_length=122)),
                ('price', models.IntegerField(max_length=122)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good.categ')),
            ],
        ),
    ]
