# Generated by Django 4.0 on 2022-09-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_categ_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
    ]
